name: 'Codecov'
description: 'GitHub Action that uploads coverage reports for your repository to codecov.io'
author: 'Ibrahim Ali <@ibrahim0814> & Thomas Hu <@thomasrockhu> | Codecov'
inputs:
  name:
    description: 'User defined upload name. Visible in Codecov UI'
    required: false
  token:
    description: 'Repository upload token - get it from codecov.io. Required only for private repositories'
    required: false
  file:
    description: 'Path to coverage file to upload'
    required: false
  files:
    description: 'Comma-separated list of files to upload'
    required: false
  directory:
    description: 'Directory to search for coverage reports.'
    required: false
  flags:
    description: 'Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)'
    required: false
  path_to_write_report:
    description: 'Write upload file to path before uploading'
    required: false
  env_vars:
    description: 'Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)'
    required: false
  fail_ci_if_error:
    description: 'Specify whether or not CI build should fail if Codecov runs into an error during upload'
    required: false
  verbose:
    description: 'Specify whether the Codecov output should be verbose'
    required: false
  bash_args:
    description: 'Extra arguments to pass into the codecov bash script.  One argument per line.'
    required: false
branding:
  color: 'red'
  icon: 'umbrella'
runs:
  using: 'node12'
  main: 'dist/index.js'
