name: 'Codecov'
description: 'GitHub Action that uploads coverage reports for your repository to codecov.io'
author: 'Ibrahim Ali <@ibrahim0814> | Codecov'
inputs: 
  name:
    description: 'User defined upload name. Visible in Codecov UI'
    required: false 
  token:
    description: 'Repository upload token - get it from codecov.io. Required only for private repositories'
    required: false 
  file:
    description: 'Path to coverage file to upload'
    required: false
  flags:
    description: 'Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)'
    required: false
  fail_ci_if_error:
    description: 'Specify whether or not CI build should fail if Codecov runs into an error during upload'
    required: false
  config:
    description: 'Path to codecov.yml config file'
    required: false
branding:
  color: 'red' 
  icon: 'umbrella'
runs:
  using: 'node12'
  main: 'dist/index.js'
   
